### ISSUE TITLE
Blender-plugins : Retopologize settings.

### ISSUE THREAD

**Issue by ZAQraven** [cgg-bern/quadwild-bimdf#12]
**System Information** Operating system: Linux-6.3.12-200.fc38.x86_64-x86_64-with-glibc2.37 64 Bits

**Blender Version** 3.6.0, branch: blender-v3.6-release, commit: [2023-06-27](https://developer.blender.org/rBc7fc78b81ecb)

**QuadWild-BiMDF** :  (0.0.1)  (2023-05-19)

***************************************

Retopogizing object relies on to basic_setup.txt instead QW's Settings in Blender. So, setting up on the panel means nothing.
Also needs some buttons for choosing between 1 - 3.

**Comment by ZAQraven** [comment]
QW's setting should be printed and saved to basic_setup.txt 
To do this, there should be saved to .txt file.

**Comment by mheistermann** [comment]
Indeed, the blender plugin is just an early draft, in fact my first attempt at a blender plugin, so not even sure if the integration this way makes a lot of sense.
I thought I'd still already put the current code out there for developers to play with, but it's really not ready for users yet.

Unfortunately, I currently don't have any time to work on the plugin, as I'm focused on finishing my thesis (this will occupy me for the next few months). However, I really would like to see our work (and by extension, the work of the QuadWild authors) being used in practice instead of being hidden in the academic ivory tower, so I do plan to work on a nice plugin in the future.

I'd be very happy to accept pull requests for any work on this though! 

Writing config files is the simplest option that doesn't involve any work on the C++ side. Here it would probably be best to run the steps separately to only re-compute the parts influenced by changed parameters. If i remember right, the main quadwild binary also did not implement reading the quad_from_patches (quantization) type config files.

I was also considering revamping the CLI (and turning quadwild+quad_from_patches into a single tool) such that every setting can be passed as commandline parameter. Reading some well-supported config format such as JSON might also make sense for easier interoperability (the current config file parser is a bit brittle anyways).

**Comment by fire** [comment]
What's your design for this?

> I was also considering revamping the CLI (and turning quadwild+quad_from_patches into a single tool) such that every setting can be passed as commandline parameter. Reading some well-supported config format such as JSON might also make sense for easier interoperability (the current config file parser is a bit brittle anyways).
